Uhrs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

urlpatterns = [
    path('',include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', RedirectView.as_view(pattern_name='index', permanent=False)),

]

main/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views 
from django.conf.urls import include
from django.views.generic.base import RedirectView



urlpatterns = [

	path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('appointment', views.form_hos, name='appointment'),
    path('appointment/details', views.past_appt, name='appointment_details'),
    path('appointment/payment', views.payment, name='payment'),
    path('login/user', views.user_login, name='user_login'),
    path('clinic/dashboard', views.clinic_dashboard, name='clinic_dashboard'),
    path('clinic/accepted', views.accepted_patient, name='clinic_accepted'),

    path('api/cities',views.get_cities, name='api_cities'),
    path('api/clinics',views.get_clinics, name='api_clinics'),
    path('api/states',views.get_states, name='api_states'),
    path('receipt/<str:ids>',views.receipt, name='receipt'),

    path('logout/', views.logout_view, name='logout'),
    path('redirect', views.redirect_ac, name='redirect'),
]

main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import uuid

from django.db import models
from django.utils.translation import ugettext as translate
from django.utils.timezone import now




GENDER_CHOICES = (
	('Male' , 'Male'),
	('Female' , 'Female'),

)

DOCTYPE_CHOICES = (
	('Cardiologist' , 'Cardiologist'),
	('Dentist' , 'Dentist'),
	('General_Physician' , 'General Physician'),
	('ENT_Specialist' , 'ENT Specialist'),
	('Obstetrics' , 'Obstetrics'),
)


class AutoCreatedUpdatedMixin(models.Model):

	created_at = models.DateTimeField(
		verbose_name=translate('created at'),
		unique=False,
		null=True,
		blank=True,
		db_index=True,
	)

	updated_at = models.DateTimeField(
		verbose_name=translate('updated at'),
		unique=False,
		null=True,
		blank=True,
		db_index=True,
	)

	class Meta:
		abstract = True

	def save(self, *args, **kwargs):
		if not self.created_at:
			self.created_at = now()
			self.updated_at = self.created_at
		else:
			auto_updated_at_is_disabled = kwargs.pop('disable_auto_updated_at', False)
			if not auto_updated_at_is_disabled:
				self.updated_at = now()
		super(AutoCreatedUpdatedMixin, self).save(*args, **kwargs)


class SoftDeleteMixin(models.Model):

	deleted_at = models.DateTimeField(
		verbose_name=translate('deleted at'),
		unique=False,
		null=True,
		blank=True,
		db_index=True,
	)

	class Meta:
		abstract = True

	def delete(self, using=None, keep_parents=False):
		self.deleted_at = now()
		kwargs = {
			'using': using,
		}
		if hasattr(self, 'updated_at'):
			kwargs['disable_auto_updated_at'] = True
		self.save(**kwargs)

class User(AbstractUser,AutoCreatedUpdatedMixin,SoftDeleteMixin):
	is_client = models.BooleanField(default=False)
	is_hospo = models.BooleanField(default=False)
	docto_id = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
	

	def save(self, *args, **kwargs):
		super(User, self).save(*args, **kwargs)
		self.docto_id = "docto19"+str(10000+int(self.id)) 
		super(User, self).save(*args, **kwargs)

class Country(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class State(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	name = models.CharField(max_length=100)
	country = models.ForeignKey(Country,on_delete=models.CASCADE)

	def __str__(self):
		return self.name + ", " + self.country.name

	def as_dict(self):
		return {
			"name":self.name,
			"id":self.id
		}

class City(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	name = models.CharField(max_length=100)
	state = models.ForeignKey(State,on_delete=models.CASCADE)

	def __str__(self):
		return self.name + ", " + self.state.name

	def as_dict(self):
		return {
			"name":self.name,
			"id":self.id
		}


class Clinic(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	user = models.ForeignKey(User, on_delete=models.CASCADE , default=None)
	name = models.CharField(max_length=50, blank=False , default=0)
	contact = models.CharField(max_length=50, blank=False , default=0)
	city = models.ForeignKey(City,on_delete=models.CASCADE, blank=False  , related_name='city_clinic', default=None)
	address = models.CharField(max_length=50, blank=False , default=0)
	fees = models.CharField(max_length=50, blank=False , default=0)

	def __str__(self):
		return self.name + " "+ self.city.name

	def as_dict(self):
		return {
			"name":self.name,
			"id":self.id
		}

class Doctor(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	name = models.CharField(max_length=50, blank=False , default=0)
	clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE , default=None , related_name='doc_clinic')
	stype = models.CharField(max_length=100, blank=False , choices=DOCTYPE_CHOICES)
	

	def __str__(self):
		return self.name + " "+ self.stype + " " + self.clinic.name

class Patient(AutoCreatedUpdatedMixin,SoftDeleteMixin):
	user = models.ForeignKey(User, on_delete=models.CASCADE , default=None)
	reg_id = models.CharField(max_length=100, blank=True, unique=True, default=uuid.uuid4)
	name = models.CharField(max_length=50, blank=False)
	age = models.CharField(max_length=50, blank=False ,default=0)
	
	gender = models.CharField(max_length=100, blank=False , choices=GENDER_CHOICES)
	clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE , default=None , related_name='user_clinic')
	doctor = models.CharField(max_length=100, blank=False , choices=DOCTYPE_CHOICES)
	father_husband_name = models.CharField(max_length=50, blank=False)
	contact = models.CharField(max_length=20, blank=False)
	adhaar = models.CharField(max_length=12, blank=False)
	epic = models.CharField(max_length=20, blank=False)
	pin = models.CharField(max_length=6, blank=False)
	email = models.EmailField(blank=False)
	address = models.CharField(max_length=100, blank=False)
	city = models.ForeignKey(City,on_delete=models.CASCADE, blank=False  , related_name='city', default=None)
	is_accepted = models.IntegerField(default=0)

	def save(self, *args, **kwargs):
		super(Patient, self).save(*args, **kwargs)
		self.reg_id = "arogya19"+str(12000+int(self.id)) 
		super(Patient, self).save(*args, **kwargs)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from main.models import Patient	, User


class PatientSignupForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('name', 'gender', 'doctor' , 'father_husband_name','contact' , 'adhaar' , 'epic' , 'pin' , 'email' , 'address' , 'city' , 'age'  , 'clinic')



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email','password1','password2')

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from main.forms import *
from main.models import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout



def index(request):
    return render(request,'layouts/main.html')

def redirect_ac(request):
    if not request.user.is_authenticated:
        return redirect('/')
    if request.user.is_client:
        return redirect('/form')
    elif request.user.is_hospo:
        return redirect('/')
    else:
        return redirect('/')

def logout_view(request):
    logout(request)
    return redirect('index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            if User.objects.filter(email=form.cleaned_data.get('email')).count() > 0:
                return render(request,"layouts/message.html",{"background":"bg-warning","title":"Error","head":"Error","body":"Email is already associated to an account."})
            else:
                user = form.save(commit=False)
                user.username = form.cleaned_data.get('email')
                user.first_name = request.POST.get('first')
                user.last_name = request.POST.get('last')
                user.is_active = True   # to make false for email verification 
                user.is_client = True
                user.save()
                raw_password = form.cleaned_data.get('password1')
                login(request, user, backend='django.contrib.auth.backends.AllowAllUsersModelBackend')
                #context = {
                    #"link": "https://techniche.org/activation_account/"+encrypt_val(str(user.id)+";"+user.first_name),
                    #"name" : user.first_name + " " + user.last_name,
                    #"tid" : user.docto_id
                #}
                #content = render_to_string("emails/activate_account.html",context)
                #Send(user.email,'Confirm your Techniche Registration',content,sender="info@techniche.org",replyto="info@techniche.org",name="Techniche, IIT Guwahati")
                return render(request,"layouts/message.html",{"background":"bg-success","title":"Verify your email","head":"Verify your email","body":"A confirmation mail has been sent to the registered email. Confirm it once to register for events."})
        else:
            errors = form.errors
            data = {"email":request.POST.get('email'),"first_name":request.POST.get('first'),"last_name":request.POST.get('last')}
            form = SignupForm(initial=data)
        return render(request, 'layouts/signup.html', {'form': form,'errors':errors})
    form = SignupForm()
    return render(request, 'layouts/signup.html', {'form': form})



def user_login(request):
    

    if request.method=="POST":
        username = User.objects.filter(email=request.POST['email']).first().username
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user, backend='django.contrib.auth.backends.AllowAllUsersModelBackend')
            if request.user.is_client: 
                return redirect('/appointment')
            else:
                return redirect('/clinic/dashboard')
        else:
            return render(request, 'layouts/user_login.html',{"messages":[["text-danger","Invalid Credentials."]]})
    return render(request, 'layouts/user_login.html')


@login_required
def form_hos(request):

    if request.user.is_client:

        if request.method == "POST":
            form = PatientSignupForm(request.POST)
            if form.is_valid():
                patient = form.save(commit=False)
                patient.user_id = request.user.id
                patient.save()
                #return redirect('/receipt/'+str(patient.id))
                return render(request,"layouts/message.html",{"background":"bg-success","title":"Appointed Submitted","head":"Appointed Submitted","body":"Wait for appointment to be confirmed."})
                #return HttpResponse('form submitted')
            else:
                errors = form.errors
                data = {"email":request.POST.get('email'),"first_name":request.POST.get('name'),"last_name":request.POST.get('age')}
                form = PatientSignupForm(initial=data)

            return render(request, 'form_hos.html', {'form': form,'errors':errors})


        else:        
            form = PatientSignupForm()

        countries = Country.objects.all()
        genders = [x[0] for x in GENDER_CHOICES]
        doctors = [x[0] for x in DOCTYPE_CHOICES]
        return render(request, 'form_hos.html', {'form': form ,'genders':genders, 'doctors':doctors , 'countries':countries})

    else:
        return redirect('/')

   


def get_cities(request):
    if request.method=="POST":
        state_id = request.POST.get('state')
        state = State.objects.filter(id=int(state_id)).first()
        cities = City.objects.filter(state=state).order_by('name')
        data = [city.as_dict() for city in cities]
        return JsonResponse(data,safe=False)

def get_states(request):
    if request.method=="POST":
        country_id = request.POST.get('country')
        country = Country.objects.filter(id=int(country_id)).first()
        states = State.objects.filter(country=country).order_by('name')
        data = [state.as_dict() for state in states]
        return JsonResponse(data,safe=False)

def get_clinics(request):
    if request.method=="POST":
        city_id = request.POST.get('city')
        city = City.objects.filter(id=int(city_id)).first()
        clinics = Clinic.objects.filter(city=city).order_by('name')
        data = [clinic.as_dict() for clinic in clinics]
        return JsonResponse(data,safe=False)
        
@login_required
def receipt(request , ids):
    p_id = ids
    patient = Patient.objects.filter(id=p_id).first()
    return render(request , 'receipt.html' , {'patient':patient})


def clinic_dashboard(request):

    user = User.objects.filter(id=request.user.id , is_hospo=True).first()
    patients = Patient.objects.all()
    clinic = Clinic.objects.filter(user_id = request.user.id).first()

    if user is not None:

        if request.method == "POST":

            identifier = request.POST.get('extra_id')
            tr_id = request.POST.get('tr_id')
            patient = Patient.objects.filter(id=int(tr_id)).first()

            if int(identifier)==1:
                patient.is_accepted = 1
                #context = {
                    #"link": "https://techniche.org/techrep/activation/"+encrypt_val(str(techrep.user.id)+";"+techrep.user.first_name),
                    #"name" : techrep.user.first_name + " " + techrep.user.last_name,
                    #"tid" : techrep.user.t_id
                #}
                #content = render_to_string("emails/techrep_confirmation.html",context)
                #Send(techrep.email,'Techrep Registration Approved',content,sender="pr@techniche.org",replyto="pr@techniche.org",name="Techniche, IIT Guwahati")
                patient.save()
                return HttpResponse(tr_id)

            elif int(identifier)==0:
                patient.is_accepted = -1
                patient.save()
                return HttpResponse(tr_id)


        return render(request , "clinic/dashboard.html", {'patients':patients , 'clinic':clinic})

    else :
        return HttpResponse("Not Authorized") 


def accepted_patient(request):

    usr = User.objects.filter(id=request.user.id , is_hospo=True).first()
    data = Patient.objects.all()
    clinic = Clinic.objects.filter(user_id = request.user.id).first()

    if usr is not None:

        return render(request , "clinic/accepted.html" ,{'patients' :data})

    else :
        return HttpResponse("Not Authorized") 

def past_appt(request):
    pre_all = Patient.objects.filter(user_id=request.user.id).all().order_by('-id')
    clinic = Clinic.objects.filter(user_id = request.user.id).first()
    return render(request, 'past_appt.html', {'pre_all':pre_all , 'clinic':clinic})

def payment(request):
    return render(request,'payment.html')

main/templates/base.html
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    {%load static%}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117122242-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-117122242-1');
  </script>

  <title>{%block title%}{%endblock%}</title>
  <meta name="description" content="Techniche">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/normalize.css@8.0.0/normalize.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/pixeden-stroke-7-icon@1.2.3/pe-icon-7-stroke/dist/pe-icon-7-stroke.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.0/css/flag-icon.min.css">
 
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->
  <style type="text/css">
      #main-content{
        min-height:calc(100vh - 90px);
        padding:10px;
    }
    .margin-auto{
        margin:auto;   
    }
</style>
{%block head%}{%endblock%}

</head>
<body>

    <!-- Right Panel -->

    <div id="right-panel" class="right-panel" style="margin-top:0px; margin-left:0px;">


        <!-- Header-->
        <div id="main-content">
            {%block content%}
            {%endblock%}
        </div>
        <!--         <div class="clearfix"></div> -->


    </div><!-- /#right-panel -->

    <!-- Right Panel -->

    <!-- Scripts -->

    <script src="https://cdn.jsdelivr.net/npm/jquery@2.2.4/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.4/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-match-height@0.7.2/dist/jquery.matchHeight.min.js"></script>
   
    <script type="text/javascript">
        $("#main-content").css('min-height', ($(window).innerHeight()-$("#header").height()-$(".site-footer").height()).toString()+'px');
        $(window).resize(function(){ 
            $("#main-content").css('min-height', ($(window).innerHeight()-$("#header").height()-$(".site-footer").height()).toString()+'px');
        });
    </script>
    {%block script%}
    {%endblock%}

</body>
</html>

main/templates/form_hos.html
{% extends 'layouts/clinic_master.html' %}

{% block title %}Form{% endblock %}

{% block content %}

<div class="row" style="margin-left:0px; margin-right: 0px;">
	<div class="col-md-2"></div>
	<div class="col-xs-12 col-md-8">
		<div class="card">
			<div class="card-body card-block">
				<form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
					
					
					<div class="row form-group">
						<div class="col col-md-3"><img style="border-radius:100%; width: 80px;" src="{{request.user.avatar}}"></div>
						<div class="col-12 col-md-9" style="padding-top: 16px;">
							<strong><H2><b>&nbsp; APPOINTMENT &nbsp; FORM </b></H2></strong>
						</div>
					</div>

					{%csrf_token%}
					<hr>
					<div class="card danger text-center" style="background-color:#bacfef; padding-top:8px;"> <h5><B> Patient Details </B></h5> </div>
					<br>
					<div class="row form-group">
						<div class="col col-md-2"> <label for="id_name" class=" form-control-label">Patient's Name:</label></div>
						<div class="col col-md-4"><input type="text" id="id_name" name="name" placeholder="Enter patient's name" class="form-control" required></div>
						<div class="col-12 col-md-1"></div>
						<div class="col-12 col-md-1"><label for="id_gender" class=" form-control-label"> Gender:</label></div>
						<div class="col-12 col-md-4">
							<select name="gender" id="id_gender" class="form-control">
								<option value="">Select</option>
								{%for gender in genders%}
								<option value="{{gender}}">{{gender}}</option>
								{%endfor%}      
							</select>
						</div>
					</div>
					<br>
					<div class="row form-group">
						<div class="col col-md-2"><label for="id_father_husband_name" class=" form-control-label">Father/Husband Name:</label></div>
						<div class="col-12 col-md-4"><input type="text" id="id_father_husband_name" name="father_husband_name" placeholder="" class="form-control" required></div>
						<div class="col-12 col-md-1"></div>
						<div class="col col-md-1"><label for="id_age" class=" form-control-label">Age:</label></div>
						<div class="col-12 col-md-4 input-group">	
							<input type="text" max-length="10" id="id_age" name="age" placeholder="" class="form-control" required>
						</div>
					</div>

					<div class="card danger text-center" style="background-color:#bacfef; padding-top:8px;"> <h5><B> Patient Address & Contact </B></h5> </div>
					<br>
					<div class="row form-group">
						<div class="col col-md-2"><label for="id_email" class=" form-control-label">Email Address:</label></div>
						<div class="col-12 col-md-4">
							<input type="email" id="id_email" name="email" placeholder="Enter Email" class="form-control" required>
							<small class="help-block form-text">Please enter patients email</small>
						</div>
						<div class="col-12 col-md-1"></div>
						<div class="col col-md-1"><label for="id_contact" class=" form-control-label">Contact:</label></div>
						<div class="col-12 col-md-4 input-group">	
							<input type="text" max-length="10" id="id_contact" name="contact" placeholder="Enter Here" class="form-control" required>
						</div>
					</div>

					<div class="row form-group">
						<div class="col col-md-2"><label for="id_country" class=" form-control-label">Country:</label></div>
						<div class="col-12 col-md-4">
							<select name="country" id="id_country" class="form-control" required>
								<option value="">Select Country</option>
								{%for country in countries%}
								<option value="{{country.id}}">{{country.name}}</option>
								{%endfor%}      
							</select>
						</div>
						<div class="col-12 col-md-1"></div>
						<div class="col col-md-1"><label for="id_state" class=" form-control-label">State:</label></div>
						<div class="col-12 col-md-4">
							<select name="states" id="id_state" class="form-control" required>
								<option value="0">Select State</option>   
							</select>
						</div>
					</div>

					<div class="row form-group">

					</div>

					<div class="row form-group">
						<div class="col col-md-2"><label for="id_city"  class=" form-control-label">City:</label></div>
						<div class="col-12 col-md-4">
							<select name="city" id="id_city" class="form-control" required>
								<option value="0">Select City</option>
							</select>
						</div>
						<div class="col-12 col-md-1"></div>
						<div class="col col-md-1"><label for="id_pin" class=" form-control-label">Pin:</label></div>
						<div class="col-12 col-md-4"><input type="text" id="id_pin" name="pin" placeholder="Pin Code" class="form-control" required></div>
					</div>

					<div class="row form-group">
						<div class="col col-md-2"><label for="id_address" class=" form-control-label"> Address:</label></div>
						<div class="col-12 col-md-10"><textarea name="address" id="id_address" rows="3" placeholder="Enter Address Here" class="form-control" required></textarea></div>
					</div>

					<div class="card danger text-center" style="background-color:#bacfef; padding-top:8px;"> <h5><B>  Patient's Identity </B></h5> </div>
					<br>
					<div class="row form-group">
						<div class="col col-md-2"><label for="id_epic" class=" form-control-label"> EPIC No:</label></div>
						<div class="col-12 col-md-4">
							<input type="text"  id="id_epic" name="epic" placeholder="" class="form-control" required>
						</div>
						<div class="col-12 col-md-1"></div>
						<div class="col col-md-1"><label for="id_adhaar" class=" form-control-label">Adhaar No:</label></div>
						<div class="col-12 col-md-4 input-group">	
							<input type="text" max-length="12" id="id_adhaar" name="adhaar" placeholder="" class="form-control" required>
						</div>

					</div>

					<div class="card danger text-center" style="background-color:#bacfef; padding-top:8px;"> <h5><B>  Doctor & Fees Details </B></h5> </div>
					<br>

					<div class="row form-group">
						<div class="col col-md-2"><label for="id_doctor" class=" form-control-label"> Doctor Type:</label></div>
						<div class="col-12 col-md-4">
							<select name="doctor" id="id_doctor" class="form-control">
								<option value="">Select</option>
								{%for doctor in doctors%}
								<option value="{{doctor}}">{{doctor}}</option>
								{%endfor%}      
							</select>
						</div>

						<div class="col-12 col-md-1"></div>
						<div class="col col-md-1"><label for="id_fees" class=" form-control-label">Fees:</label></div>
						<div class="col-12 col-md-4 input-group">	
							<input type="text" max-length="10" id="id_fees" name="fees" placeholder="" class="form-control" required>
						</div>

					</div>
					<div class="row form-group">
						<div class="col col-md-2"><label for="id_clinic"  class=" form-control-label">Clinic:</label></div>
						<div class="col-12 col-md-4">
							<select name="clinic" id="id_clinic" class="form-control" required>
								<option value="0">Select Clinic/Hospital</option>
							</select>
						</div>
					</div>


					<div class="row">
					<div class="col-xs-3 col-sm-3"></div>
					<div class="col-xs-6 col-sm-6 text-center">
						<button type="submit" name="submit" class="btn btn-success" onclick="extraval();">Submit</button>
					</div>
					<div class="col-xs-3 col-sm-3"></div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="col-md-2"></div>
</div>

{% endblock %}
{%block script%}
<script type="text/javascript">

	$("#user_dash").addClass('active');

   $("#id_state").prop('disabled',true);

    $("#id_country").on('change',function(){
        url = "{%url 'api_cities'%}"
        text1 = $('#id_country').val();
        if(text1===""){
            $("#id_state").prop('disabled',true);
            $("#id_state").empty()
            $("#id_state").append('<option value="">Select State</option>');

        }
        else{
            $.ajax({
                type: "POST",
                url: "{%url 'api_states'%}",
                data: {'country':text1,csrfmiddlewaretoken:'{{ csrf_token }}'},
                success: function(states){
                    $("#id_state").prop('disabled',false);
                    $("#id_state").empty()
                    $("#id_state").append('<option value="">Select State</option>');
                    for(state in states){
                        $("#id_state").append('<option value="'+states[state]['id']+'">'+states[state]['name']+'</option>');
                    }
                }
            });
        }
    });

    $("#id_city").prop('disabled',true);
    $("#id_state").on('change',function(){
        url = "{%url 'api_cities'%}"
        text = $('#id_state').val();
        if(text===""){
            $("#id_city").prop('disabled',true);
            $("#id_city").empty()
            $("#id_city").append('<option value="">Select City</option>');
        }
        else{
            $.ajax({
                type: "POST",
                url: "{%url 'api_cities'%}",
                data: {'state':text,csrfmiddlewaretoken:'{{ csrf_token }}'},
                success: function(cities){
                    $("#id_city").prop('disabled',false);
                    $("#id_city").empty()
                    $("#id_city").append('<option value="">Select City</option>');
                    for(city in cities){
                        $("#id_city").append('<option value="'+cities[city]['id']+'">'+cities[city]['name']+'</option>');
                    }
                }
            });
        }
    });


     $("#id_clinic").prop('disabled',true);
    $("#id_city").on('change',function(){
        url = "{%url 'api_clinics'%}"
        text = $('#id_city').val();
        if(text===""){
            $("#id_clinics").prop('disabled',true);
            $("#id_clinics").empty()
            $("#id_clinics").append('<option value="">Select City</option>');
        }
        else{
            $.ajax({
                type: "POST",
                url: "{%url 'api_clinics'%}",
                data: {'city':text,csrfmiddlewaretoken:'{{ csrf_token }}'},
                success: function(clinics){
                    $("#id_clinic").prop('disabled',false);
                    $("#id_clinic").empty()
                    $("#id_clinic").append('<option value="">Select City</option>');
                    for(clinic in clinics){
                        $("#id_clinic").append('<option value="'+clinics[clinic]['id']+'">'+clinics[clinic]['name']+'</option>');
                    }
                }
            });
        }
    });

</script>
{%endblock%}

main/templates/sidebar.html
<li>
	<a href="#"><b>User Portal</b> </a>
</li>
<li id="user_dash">
	<a href="{%url 'appointment'%}" ><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
</li>
<li class="menu-title">{{request.user.first_name}} {{request.user.last_name}}</li><!-- /.menu-title -->
<li id="user_work-past"><a href="{%url 'appointment_details'%}"><i class="menu-icon fa fa-desktop"></i> Past Appointments</a></li>
<li id="user_work-payment"><a href="{%url 'payment'%}"><i class="menu-icon fa fa-money"></i> Payment</a></li>